--- #YAML:1.0
name:                Crypt-PerfectPaperPasswords
version:             0.05
abstract:            Steve Gibson's Perfect Paper Passwords
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36_01
distribution_type:   module
requires:     
    Crypt::Rijndael:               0
    Digest::SHA256:                0
    Getopt::Long:                  0
    Pod::Usage:                    0
    Scalar::Util:                  0
    Test::More:                    0
    Time::HiRes:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Andy Armstrong <andy@hexten.net>
